workflows:
  android-workflow:
    name: Android Workflow
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
        GRADLE_USER_HOME: /root/.gradle
    scripts:
      - name: Set up Android SDK
        script: |
          export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          yes | sdkmanager "platforms;android-30" "build-tools;30.0.3"
      - name: Grant execute permissions to gradlew
        script: |
          chmod +x ./gradlew
      - name: Build the Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
