workflows:
  android-workflow:
    name: Android Workflow
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
        GRADLE_USER_HOME: /root/.gradle
    scripts:
      - name: Check Android SDK installation
        script: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          echo "SDK Manager version:"
          sdkmanager --version || echo "SDK Manager not found"
      - name: Build the Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
